### ISSUE TITLE
The link to the raw dataset is broken

### ISSUE THREAD

**Issue by whwjdqls** [pliang279/MultiBench#35]
Hi there, 

The link to the raw dataset for mosei and mosi which I have highlighted below, seems to be broken. 
![image](https://github.com/pliang279/MultiBench/assets/73946308/3d55bcd5-704e-43a1-81b8-23326c45ba98)

The link leads to 404.
![image](https://github.com/pliang279/MultiBench/assets/73946308/6c26e00f-f5b2-4377-b804-a30bc52518e4)

**Comment by lvyiwei1** [comment]
Thank you for pointing out this error! The correct link should be _https://github.com/matsuolab/CMU-MultimodalSDK_ . I will fix it in the README.

**Comment by whwjdqls** [comment]
Thanks for the prompt reply! :)

But it is written in the README that the raw dataset is available, but when I go to the link that you have given, https://github.com/matsuolab/CMU-MultimodalSDK, in the FAG, it says that the raw data is not available. 

![image](https://github.com/pliang279/MultiBench/assets/73946308/dc0517da-5cc6-403d-850e-6e6760696055)

is there anyway that I can get the raw data? By raw data I mean, the URL and the timestamp to the VIdeos or the downloaded videos.

**Comment by lvyiwei1** [comment]
Sorry for the confusion. They used to be available when we made MultiBench. It seems that there is an update on the CMU-MOSI/MOSEI datasets (by the authors of those datasets) about one year ago that removed access all the raw data (as shown in screenshot below). I will update the readme on MultiBench as well to reflect that. If you really need to access the raw videos instead of processed features, I would recommend directly contacting the authors of the datasets. 
![WeChat Image_20240127030641](https://github.com/pliang279/MultiBench/assets/32001651/44ff006d-f392-4948-9dc1-82c83c585640)

**Comment by whwjdqls** [comment]
Thanks for the prompt reply! :)
